### ISSUE TITLE
New token mint fails on first attempt (insufficient funds)

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#222]
Excited to mint my first token in the UI, I went to the page and clicked the button ... and fell flat on my face.

<img width="1000" alt="Screen Shot 2022-07-13 at 2 37 52 PM" src="https://user-images.githubusercontent.com/1476820/178841466-9c9a6f2e-7df7-4b0d-83ce-61f8f44f2d76.png">

I happened to know, this was because my wallet was not funded, but users are not going to know that.

see #59 -- I strongly think we should airdrop SOL to accounts that will be paying for things automatically (or load them with Amman as such). Yes, it is educational to airdrop yourself, but --

1. It is extremely annoying if you do a state reset of the local validator, and
2. It adds at least the ~15 seconds to confirm the airdrop txn to the "time to first magic" metric 
3. Having a smooth onboarding is more important and users can learn this feature later if needed

**Comment by SvenDowideit** [comment]
yeah - this is an expansion on #203 - atm, i'm not disabling buttons that the user can't afford - aridropping on startup doesn't _solve_ this, because it still fails later, when they run out again.

fun fact is that i'm doing quite a few tests on things with intentionally unfunded / underfunded accounts - as it seems very few dapps i've used have actually been tested for this, and their error handling is woeful.

the funnest senarios are where there are many transactions, and your account runs out mid way - no-one (so far) seems to recover and restart - so you've just lost a bunch of time and SOL.
