### ISSUE TITLE
Why did we go back to full length pubkey displays?

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#223]
imo, the information besides ~8 characters at front and end of the pubkey, is wasted space

![image](https://user-images.githubusercontent.com/1476820/178843394-7dfd1d13-983d-47ad-8652-23b24a2af402.png)

I'd like to take the pubkey back to 8 or so chars. There's _so_ much we can put in the UI that's more useful information that that -- human readable labels... transactions ... images representing the token mint ... which program the account belongs to... etc .

**Comment by SvenDowideit** [comment]
duuude!, that's like, your opinion man, like....


yeah - I actualy just fixed the key truncation to output the length that was requested (that code was busted badly), because there's no sense in truncating to 8 chars in the AccountView. 

the changes view looked better because the table was always massive - I presume you've changed that now?

**Comment by nathanleclaire** [comment]
> duuude!, that's like, your opinion man, like....

indeed

> the changes view looked better because the table was always massive - I presume you've changed that now?

It's a bit better out of the box -- with labels and/or owners I think it could start lookin tidier too 

<img width="1022" alt="Screen Shot 2022-07-13 at 3 16 42 PM" src="https://user-images.githubusercontent.com/1476820/178846364-5435f1c5-ce6d-4ae7-b1c2-3efceb1476d0.png">
