### ISSUE TITLE
Max Delta support seems broken

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#225]
gettin results like this on mainnet, don't feel super high pri on solving this cause it's no one's favorite feature, but wanted to note it down 

<img width="286" alt="Screen Shot 2022-07-13 at 3 20 01 PM" src="https://user-images.githubusercontent.com/1476820/178846772-59c0aef7-f794-4d6e-9497-0a8a86dc94e3.png">

**Comment by SvenDowideit** [comment]
I'm pretty sure this is because we're storing the delta and count aggregations in the same structure that we're using to cache the on-chain info, and somewhere in there (i'm guessing the program changes subscription), we're failing to get the old value.

I _think_ this will get addressed by #215 - as I _think_ i'll be rewriting that cache code, but 💯
