### ISSUE TITLE
Create local tokens and NFTs

### ISSUE THREAD

**Issue by nathanleclaire** [workbenchapp/solana-workbench#63]
We should have a nice UI to create regular old fungible tokens as well as NFTs (integrating with Metaplex).

**Comment by SvenDowideit** [comment]
https://www.brianfriel.xyz/how-to-create-a-token-on-solana/

**Comment by SvenDowideit** [comment]
I'm thinking of doing this in 2 stages

1. implement pure SPL tokens UX (ie, without metaplex, or maybe only enabling it if metaplex is loaded)
2. add metaplex support, doing the work to add a UI to browse programs on one network, and save them, and an upload to chain UI (assuming that one can do that) - otherwise, doing this will require the Dockercontainer based get code from git, build it and upload.
